// Copyright 2025–2026 Skip
// SPDX-License-Identifier: MPL-2.0
#if !SKIP_BRIDGE
import Foundation
import SwiftUI

/// A "Software Bill of Materials" view that displays the third-party software dependencies
/// of the host app, parsed from SPDX SBOM resource files in the given bundle.
///
/// The view looks for SBOM resources generated by `skip sbom create`:
///
/// - On Apple platforms: `sbom-darwin-ios.spdx.json`
/// - On Android: `sbom-linux-android.spdx.json`
///
/// Each dependency is presented as a row showing its name, supplier, version, and declared
/// license. Tapping a row navigates to a detail view that shows all SPDX fields for the
/// package, including checksums and external references. Where the declared license is a
/// recognised SPDX identifier (e.g., `EUPL-1.2`, `Apache-2.0`), the detail view exposes a
/// button that opens the corresponding page on https://spdx.org/licenses/ in an in-app
/// browser, so users can review the full license text.
///
/// The list also includes a button that brings up the system share sheet so users can
/// export the raw SPDX JSON for offline review or auditing.
///
/// `SBOMView` is intended to be dropped into a Settings or Preferences view via a
/// `NavigationLink`:
///
/// ```swift
/// NavigationLink("Bill of Materials") {
///     SBOMView(bundle: Bundle.module)
/// }
/// ```
///
/// This view exists in part to comply with open-source license obligations that require
/// distributing apps to mention the licenses of included software.
public struct SBOMView: View {
    let bundle: Bundle
    let displayMode: SBOMDisplayMode
    @State private var document: SBOMDocument? = nil
    @State private var loadError: String? = nil

    public init(bundle: Bundle, displayMode: SBOMDisplayMode = .hierarchy) {
        self.bundle = bundle
        self.displayMode = displayMode
    }

    public var body: some View {
        contentView
            .navigationTitle("Bill of Materials")
            .task {
                await loadDocument()
            }
    }

    @ViewBuilder
    private var contentView: some View {
        if let doc = document {
            SBOMListView(document: doc, bundle: bundle, displayMode: displayMode)
        } else if let error = loadError {
            SBOMEmptyView(message: error)
        } else {
            SBOMEmptyView(message: "No software bill of materials is available for this build.")
        }
    }

    private func loadDocument() async {
        do {
            let doc = try SBOMDocument.load(from: bundle)
            self.document = doc
        } catch {
            self.loadError = "Failed to parse software bill of materials: \(error.localizedDescription)"
        }
    }
}

struct SBOMEmptyView: View {
    let message: String

    var body: some View {
        VStack(spacing: 12) {
            Image(systemName: "doc.text.magnifyingglass")
                .font(.system(size: 48))
                .foregroundStyle(.secondary)
            Text(message)
                .font(.callout)
                .foregroundStyle(.secondary)
                .multilineTextAlignment(.center)
                .padding(.horizontal)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
}

// MARK: - List

struct SBOMListView: View {
    let document: SBOMDocument
    let bundle: Bundle
    @State private var displayMode: SBOMDisplayMode

    init(document: SBOMDocument, bundle: Bundle, displayMode: SBOMDisplayMode) {
        self.document = document
        self.bundle = bundle
        self._displayMode = State(initialValue: displayMode)
    }

    /// The packages shown at the top of the list, depending on the current display mode.
    private var listedPackages: [SBOMPackage] {
        switch displayMode {
        case .hierarchy:
            return document.topLevelPackages
        case .flat:
            return document.dependencyPackages
        }
    }

    var body: some View {
        List {
            // we do not show the picker on iOS because the was SBOMs are generated are always flattened (because it is derived from the Package.resolved, which does not contain any information about which packages depend on which other packages)
            #if os(Android)
            Section {
                Picker("Display Mode", selection: $displayMode) {
                    Text("Flattened").tag(SBOMDisplayMode.flat)
                    Text("Hierarchical").tag(SBOMDisplayMode.hierarchy)
                }
                .pickerStyle(.segmented)
            }
            #endif

            Section {
                ForEach(listedPackages) { pkg in
                    NavigationLink(destination: SBOMPackageDetailView(package: pkg, document: document)) {
                        SBOMPackageRow(package: pkg)
                    }
                }
            } header: {
                Text("Dependencies (\(listedPackages.count))")
            } footer: {
                Text(footerText)
            }

            Section {
                if let created = document.creationInfo?.created, !created.isEmpty {
                    SBOMFieldRow(label: "Created", value: created)
                }
                if let creators = document.creationInfo?.creators, !creators.isEmpty {
                    SBOMFieldRow(label: "Generator", value: creators.joined(separator: ", "))
                }
                if let version = document.spdxVersion, !version.isEmpty {
                    SBOMFieldRow(label: "SPDX Version", value: version)
                }
                if let dataLicense = document.dataLicense, !dataLicense.isEmpty {
                    SBOMFieldRow(label: "Data License", value: dataLicense)
                }

                SBOMShareButton(document: document, bundle: bundle)
            } header: {
                Text("About this Bill of Materials")
            }
        }
    }

    private var footerText: LocalizedStringKey {
        switch displayMode {
        case .hierarchy:
            return "This app includes the open-source software listed above. Tap a dependency to view its license, version information, and any further dependencies it brings in."
        case .flat:
            return "This app includes the open-source software listed above. Tap a dependency to view its license and version information."
        }
    }
}

struct SBOMPackageRow: View {
    let package: SBOMPackage

    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            HStack(alignment: .firstTextBaseline) {
                Text(package.name ?? "Unnamed package")
                    .font(.headline)
                    .lineLimit(1)
                Spacer()
                if let version = package.versionInfo, !SPDXLicense.isUnknown(version) {
                    Text(version)
                        .font(.caption)
                        .foregroundStyle(.secondary)
                        .lineLimit(1)
                }
            }
            if let supplier = package.supplier, !SPDXLicense.isUnknown(supplier) {
                Text(prettySupplier(supplier))
                    .font(.caption)
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
            }
            if let license = package.licenseDeclared, !SPDXLicense.isUnknown(license) {
                Text(license)
                    .font(.caption2)
                    .padding(.horizontal, 6)
                    .padding(.vertical, 2)
                    .background(Color.secondary.opacity(0.15))
                    .clipShape(Capsule())
            }
        }
        .padding(.vertical, 2)
    }

    /// Strips the SPDX `Organization:` / `Person:` prefix from a supplier string.
    private func prettySupplier(_ supplier: String) -> String {
        if supplier.hasPrefix("Organization: ") {
            return String(supplier.dropFirst("Organization: ".count))
        }
        if supplier.hasPrefix("Person: ") {
            return String(supplier.dropFirst("Person: ".count))
        }
        return supplier
    }
}

// MARK: - Detail

struct SBOMPackageDetailView: View {
    let package: SBOMPackage
    let document: SBOMDocument

    @State private var browserPresented = false
    @State private var browserURL: URL = URL(string: "https://spdx.org/licenses/")!

    var body: some View {
        List {
            Section {
                if let name = package.name, !name.isEmpty {
                    SBOMFieldRow(label: "Name", value: name)
                }
                if let version = package.versionInfo, !SPDXLicense.isUnknown(version) {
                    SBOMFieldRow(label: "Version", value: version)
                }
                if let supplier = package.supplier, !SPDXLicense.isUnknown(supplier) {
                    SBOMFieldRow(label: "Supplier", value: supplier)
                }
                if let originator = package.originator, !SPDXLicense.isUnknown(originator) {
                    SBOMFieldRow(label: "Originator", value: originator)
                }
                if let purpose = package.primaryPackagePurpose, !purpose.isEmpty {
                    SBOMFieldRow(label: "Purpose", value: purpose)
                }
                if let id = package.SPDXID, !id.isEmpty {
                    SBOMFieldRow(label: "SPDX ID", value: id)
                }
            } header: {
                Text("Package")
            }

            Section {
                if let declared = package.licenseDeclared, !SPDXLicense.isUnknown(declared) {
                    SBOMFieldRow(label: "Declared", value: resolveLicenseName(declared))
                }
                if let concluded = package.licenseConcluded, !SPDXLicense.isUnknown(concluded) {
                    SBOMFieldRow(label: "Concluded", value: resolveLicenseName(concluded))
                }
                if let copyright = package.copyrightText, !SPDXLicense.isUnknown(copyright) {
                    SBOMFieldRow(label: "Copyright", value: copyright)
                }
                if let comments = package.licenseComments, !comments.isEmpty {
                    SBOMFieldRow(label: "Comments", value: comments)
                }
                if let licenseURL = licensePageURL() {
                    Button {
                        self.browserURL = licenseURL
                        self.browserPresented = true
                    } label: {
                        Text("View License on spdx.org")
                    }
                }
                // Show extracted-license details for LicenseRef-… ids
                if let extracted = extractedLicenseInfo() {
                    if let name = extracted.name, !name.isEmpty {
                        SBOMFieldRow(label: "License Name", value: name)
                    }
                    if let text = extracted.extractedText, !text.isEmpty {
                        SBOMFieldRow(label: "License Text", value: text)
                    }
                    if let seeAlsos = extracted.seeAlsos {
                        ForEach(seeAlsos.map { SBOMSeeAlsoItem(id: "seeAlso-\($0)", url: $0) }) { item in
                            SBOMFieldRow(label: "See Also", value: item.url)
                        }
                    }
                }
            } header: {
                Text("License")
            } footer: {
                Text("Tap “View License on spdx.org” to read the full text of recognised open-source licenses.")
            }

            let subDependencies = document.directDependencies(of: package)
            if !subDependencies.isEmpty {
                Section {
                    ForEach(subDependencies) { dep in
                        NavigationLink(destination: SBOMPackageDetailView(package: dep, document: document)) {
                            SBOMPackageRow(package: dep)
                        }
                    }
                } header: {
                    Text("Dependencies (\(subDependencies.count))")
                } footer: {
                    Text("These packages are pulled in transitively by \(package.name ?? "this package").")
                }
            }

            if let download = package.downloadLocation, !SPDXLicense.isUnknown(download) {
                Section {
                    SBOMFieldRow(label: "Download", value: download)
                    if let homepage = package.homepage, !homepage.isEmpty {
                        SBOMFieldRow(label: "Homepage", value: homepage)
                    }
                    if let description = package.description, !description.isEmpty {
                        SBOMFieldRow(label: "Description", value: description)
                    }
                    if let summary = package.summary, !summary.isEmpty {
                        SBOMFieldRow(label: "Summary", value: summary)
                    }
                } header: {
                    Text("Source")
                }
            }

            if let refs = package.externalRefs, !refs.isEmpty {
                Section {
                    ForEach(refs.indices.map { SBOMIndexedItem(id: "ref-\($0)", index: $0) }) { item in
                        SBOMExternalRefRow(ref: refs[item.index])
                    }
                } header: {
                    Text("External References")
                }
            }

            if let checksums = package.checksums, !checksums.isEmpty {
                Section {
                    ForEach(checksums.indices.map { SBOMIndexedItem(id: "checksum-\($0)", index: $0) }) { item in
                        SBOMChecksumRow(checksum: checksums[item.index])
                    }
                } header: {
                    Text("Checksums")
                }
            }
        }
        .navigationTitle(package.name ?? "Package")
        #if !SKIP
        #if os(iOS)
        .navigationBarTitleDisplayMode(.inline)
        #endif
        #endif
        .openWebBrowser(isPresented: $browserPresented, url: browserURL, mode: .embeddedBrowser(params: nil))
    }

    private func licensePageURL() -> URL? {
        if let url = SPDXLicense.licensePageURL(for: package.licenseDeclared) {
            return url
        }
        return SPDXLicense.licensePageURL(for: package.licenseConcluded)
    }

    /// Looks up an extracted license info entry if the package's `licenseDeclared`
    /// or `licenseConcluded` is a `LicenseRef-…` identifier.
    private func extractedLicenseInfo() -> SBOMExtractedLicense? {
        let candidates = [package.licenseDeclared, package.licenseConcluded]
        for candidate in candidates {
            guard let id = candidate, id.hasPrefix("LicenseRef-") else { continue }
            if let info = document.extractedLicense(forId: id) {
                return info
            }
        }
        return nil
    }

    /// If the given license id is a `LicenseRef-…`, return its human-readable name when available.
    private func resolveLicenseName(_ license: String) -> String {
        if license.hasPrefix("LicenseRef-") {
            if let info = document.extractedLicense(forId: license), let name = info.name, !name.isEmpty {
                return "\(name) (\(license))"
            }
        }
        return license
    }
}

struct SBOMExternalRefRow: View {
    let ref: SBOMExternalRef

    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            if let type = ref.referenceType, !type.isEmpty {
                Text(type)
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            if let locator = ref.referenceLocator, !locator.isEmpty {
                Text(locator)
                    .font(.footnote)
                    #if !SKIP
                    .textSelection(.enabled)
                    #endif
            }
        }
        .padding(.vertical, 2)
    }
}

struct SBOMChecksumRow: View {
    let checksum: SBOMChecksum

    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            if let alg = checksum.algorithm, !alg.isEmpty {
                Text(alg)
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }
            if let value = checksum.checksumValue, !value.isEmpty {
                Text(value)
                    .font(.system(.footnote, design: .monospaced))
                    .lineLimit(1)
                    .truncationMode(.middle)
                    #if !SKIP
                    .textSelection(.enabled)
                    #endif
            }
        }
        .padding(.vertical, 2)
    }
}

// MARK: - ForEach helper items
//
// SwiftUI's `List` becomes a Compose `LazyColumn` on Android. Multiple `ForEach`
// blocks inside the same `List` share a single key namespace, so using `\.offset`
// or array indices in more than one `ForEach` causes a Compose
// `IllegalArgumentException: Key "0" was already used` crash when the list is
// scrolled. These small `Identifiable` wrappers give each row a globally unique
// string id within the enclosing list.

struct SBOMSeeAlsoItem: Identifiable, Hashable {
    let id: String
    let url: String
}

struct SBOMIndexedItem: Identifiable, Hashable {
    let id: String
    let index: Int
}

// MARK: - Shared row helpers

struct SBOMFieldRow: View {
    let label: LocalizedStringKey
    let value: String

    var body: some View {
        VStack(alignment: .leading, spacing: 2) {
            Text(label)
                .font(.caption)
                .foregroundStyle(.secondary)
            Text(value)
                .font(.callout)
                #if !SKIP
                .textSelection(.enabled)
                #endif
        }
        .padding(.vertical, 2)
    }
}

// MARK: - Share

struct SBOMShareButton: View {
    let document: SBOMDocument
    let bundle: Bundle

    var body: some View {
        if let text = sbomText() {
            ShareLink(item: text,
                      subject: Text("Software Bill of Materials"),
                      message: Text(document.name ?? "SBOM")) {
                Label("Share Bill of Materials", systemImage: "square.and.arrow.up")
            }
        }
    }

    /// Returns the raw SPDX JSON text for the bundle's SBOM, if available, falling back to
    /// re-encoding the parsed `document` if the original bytes cannot be read.
    private func sbomText() -> String? {
        if let data = SBOMDocument.rawData(from: bundle), let s = String(data: data, encoding: .utf8) {
            return s
        }
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        if let data = try? encoder.encode(document), let s = String(data: data, encoding: .utf8) {
            return s
        }
        return nil
    }
}

#endif // !SKIP_BRIDGE
